### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by model-fps** [BFeng14/ActFound#14]
Hi,author:
I tried to run In-domain bioactivity prediction experiments on pQSAR-ChEMBL, but I encountered an error as follow:
![DATA_PATH](https://github.com/user-attachments/assets/230576cf-d945-424f-a37d-f924d72c2290)
It seems to be because in the `data_pqsar_Assay_reg.py` file 
`self.split_name_train_val_test = pickle.load(open(f“{DATA_PATH}/pQSAR/drug_split_id_group1.pickle”, “rb”))` the variable name `DATA_PATH`  was not defined, so I defined `DATA_PATH` in that file as `DATA_PATH = “. /datas"`.
After re-running the command another error was reported:
```
4079 76 100
9252 187.1153936545241
Traceback (most recent call last):
  File "main_reg.py", line 307, in <module>
    main()
  File "main_reg.py", line 245, in main
    model.prepare_knn_maml(dataloader)
  File "/mnt/sda/yangqing/ActFound_e3fp_env/learning_system/system_actfound.py", line 272, in prepare_knn_maml
    self.train_assay_feat_all = torch.stack(assay_feat_list, dim=0)
RuntimeError: stack expects a non-empty TensorList
```
What is causing this and how do I fix this error?
Thanks!

**Comment by BFeng14** [comment]
Hi, it seems that your are using the wrong assay feature file. I only uploaded the assay feature+assay index file for chembl, and you may need to generate those for qpsar and bdb dataset. you can simply set --train_assay_feat_all and --train_assay_idxes to an empty file, and this code will generate them automatically. 

BTW, generating this file will cost hours, if you want to run experiments faster, you can delete ${PQSAR_KNN_MAML} in the running script. as shown in the Supplementary Figure 8 of our paper, this will lead to roughly 2% drop in performance.

**Comment by model-fps** [comment]
Thanks for the advice, problem solved！
