### ISSUE TITLE
How to fine-tune and make prediction on our own dataset?

### ISSUE THREAD

**Issue by mengtinghuang** [BFeng14/ActFound#5]
We are very interested in your work. Currently, we have a project with some experimental data and activity data. How can we fine-tune using this data and make activity predictions on molecules that have not undergone biological experiments?

**Comment by BFeng14** [comment]
Hi~ I have updated the colab programming tool for more easy usage, now you can simply fine-tune and make activity prediction on your own data. BTW, I also provide a metric (first step loss) to help you predict if Actfound can work well on your data. Please let me know if you have any further questions.

https://colab.research.google.com/drive/1zn3U3xwLXZjZQYGVgtxCiEwt1hkho62l?usp=sharing
